### ISSUE TITLE
Wire up Remove Asset from Portfolio

### ISSUE THREAD

**Issue by leongaban** [CoinHover/coinhover.io#29]
![screen shot 2017-07-02 at 10 40 40 pm](https://user-images.githubusercontent.com/191636/27777334-86f024f4-5f77-11e7-9a10-05795ae227ca.png)

**Comment by leon-yum** [comment]
https://github.com/CoinHover/coinhover.io/commit/a9e0d251c3d7770e410911c287ff05eb8e6c1459
