### ISSUE TITLE
Make sure that price value limits to 2 decimals

### ISSUE THREAD

**Issue by leongaban** [CoinHover/coinhover.io#45]
Ether price is displaying 3 decimal places

![screen shot 2017-07-10 at 7 20 28 am](https://user-images.githubusercontent.com/191636/28017783-58599e08-6540-11e7-9ab5-9c25e186654a.png)

**Comment by leon-yum** [comment]
Fixed: https://github.com/CoinHover/coinhover.io/commit/c7e961bc1e41a8adfbbd13c8f749ce67b839611c
